# devboard.spec
# ─────────────────────────────────────────────────────────────────────────────
# PyInstaller spec shared by all three build scripts.
# Usage (from each build script — don't run directly):
#   pyinstaller devboard.spec
#
# Produces a single-file executable: dist/devboard[.exe]
# ─────────────────────────────────────────────────────────────────────────────

import sys
from pathlib import Path

# The entry-point: we bundle BOTH setup.py and dashboard.py.
# The launcher (see _launcher.py generated by the build scripts) picks which
# one to run based on whether config.json already exists.
block_cipher = None

a = Analysis(
    ['_launcher.py'],           # generated by the build script
    pathex=[str(Path('.').resolve())],
    binaries=[],
    datas=[
        # Include all .py sources so users can inspect / extend them
        ('dashboard.py',   '.'),
        ('setup.py',       '.'),
        ('uninstall.py',   '.'),
    ],
    hiddenimports=[
        # Flask internals sometimes missed by the hook
        'flask',
        'flask.templating',
        'werkzeug',
        'werkzeug.serving',
        'werkzeug.routing',
        'jinja2',
        'jinja2.ext',
        'click',
        # psutil platform modules
        'psutil',
        'psutil._common',
        'psutil._pslinux',
        'psutil._psosx',
        'psutil._pswindows',
        # webview
        'webview',
        # stdlib used at runtime
        'http.server',
        'urllib.parse',
        'hashlib',
        'secrets',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # Trim size: exclude test suites and docs
        'unittest',
        'doctest',
        'pydoc',
        'tkinter',
        'numpy',
        'pandas',
        'matplotlib',
        'scipy',
        'PIL',
        'cv2',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='devboard',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,           # compress (install upx for smaller binaries)
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,       # keep console so setup wizard output is visible
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    # Windows-only: embed an icon if it exists
    icon='icon.ico' if sys.platform == 'win32' and Path('icon.ico').exists() else None,
)

# macOS: also produce a .app bundle (the build_mac.sh script then wraps in .dmg)
if sys.platform == 'darwin':
    app = BUNDLE(
        exe,
        name='DevBoard.app',
        icon='icon.icns' if Path('icon.icns').exists() else None,
        bundle_identifier='com.devboard.app',
        info_plist={
            'NSHighResolutionCapable': True,
            'CFBundleShortVersionString': '10.0',
            'CFBundleVersion': '10.0.0',
            'NSHumanReadableCopyright': 'MIT License',
        },
    )
